name: serenity_tasks
description: "A new Flutter project."
publish_to: 'none' 

version: 1.1.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  awesome_snackbar_content: ^0.1.3
  provider: ^6.1.2
  cloud_firestore: ^5.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  file_selector: ^1.0.3
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  rename_app: ^1.6.1
  file_selector_windows: ^0.9.3+2


  
#   flutter_launcher_icons: ^0.14.1

# flutter_launcher_icons:
#   #  image_path: "assets/images/icon-128x128.png"
#   image_path: "assets/icons/prompt----design-a-modern-and-sleek-logo-for-a-to-.png"
#   image_path_android: "assets/icons/prompt----design-a-modern-and-sleek-logo-for-a-to-.png"
#   # image_path_ios: "assets/images/icon-1024x1024.png"
#   # android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
#   # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#   # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
#   # adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
#   # adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
#   # background_color_ios: "#ffffff"
#   windows:
#     generate: true
#     image_path: "assets/icons/prompt----design-a-modern-and-sleek-logo-for-a-to-.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   # web:
#   #   generate: true
#   #   image_path: "assets/images/icon-1024x1024.png"
#   #   background_color: "#hexcode"
#   #   theme_color: "#hexcode"
  
#   # macos:
#   #   generate: true
#   #   image_path: "assets/images/icon-1024x1024.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/prompt----design-a-modern-and-sleek-logo-for-a-to-.png
    - assets/icons/
    - assets/icons/delete_icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/GothamBold.ttf
  #       - asset: assets/fonts/GothamBoldItalic.ttf
  #       - asset: assets/fonts/GothamBook.ttf
  #       - asset: assets/fonts/GothamBookItalic.ttf
  #       - asset: assets/fonts/GothamLight.ttf
  #       - asset: assets/fonts/GothamLightItalic.ttf
  #       - asset: assets/fonts/GothamMedium_1.ttf
  #       - asset: assets/fonts/GothamMedium.ttf
  #       - asset: assets/fonts/GothamMediumItalic.ttf
  #         style: italic
          
